# -*- coding: utf-8 -*-
"""ProjAnáliseExp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sOAb9IXi-N4Tz_---kLsICZjT7W1xfxv
"""

!pip install quickda

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
from quickda.explore_data import *

"""# Análise Univariada : escolhemos a variável "pontuacao", que é uma classificação geral de cada localidade  da pesquisa em relação à Transparência no Combate à COVID-19. """

df = pd.read_excel("dados.xlsx", sheet_name="Estados - 3ª avaliação (julho)", skiprows=range(0,2)) #Corrigimos a organização das linhas com o parâmetro skiprow. Asssim, pulamos as duas primeiras linhas, que não nos interessavam. 
df

explore(df, method= 'summarize')

df2 = df.rename(columns={"Unnamed: 0":"Estado", "Unnamed: 35":"Pontuacao", "Unnamed: 36":"Nota"}) #Corrigimos a nomenclatura das colunas 

df2

from quickda.clean_data import *

df = clean(df2, method="standardize")
df

from quickda.explore_data import *

df['pontuacao'].describe()

plt.figure(figsize=(10,5)) 
sns.boxplot(x='pontuacao',data=df)
plt.show()

"""# Análise Bivariada : comparamos a variável pontuação em relação ao tempo"""

df3 = pd.read_excel("dados_localidades(2).xlsx")
df3

maio = df3.query('Data == "Maio"')
maio.describe()

junho = df3.query('Data == "junho"')
junho.describe()

import altair as alt

alt.Chart(df3).mark_bar().encode(
    x = alt.X('Data', title='', sort=['Maio', 'junho', 'julho']),
    y = 'Ponto',
    color = 'Data',
    column = 'Estado',
    tooltip = 'Ponto',
).properties()

df3.sort_values("Estado")

plt.figure(figsize=(10,5)) 
sns.boxplot(
    x='Ponto',
    y='Data',
    data=df3)
plt.show()